[project]
name = "eda-estudos"
version = "0.1.0"
description = "Projeto para estudar EDA"
readme = "README.MD"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
]
